name: "salondjd-webapp"


services:
  salondjd-webapp:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: production-build
    ports:
      - "80:80"
    environment:
      CONTENT_API_URL: "https://strapi.salondjd.sn"
      CONTENT_API_KEY: "key"

